# Generated by Django 6.0.1 on 2026-02-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_binder_pokemoncard_binder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokemoncard",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="pokemoncard",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
