# Generated by Django 6.0.1 on 2026-02-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_alter_pokemoncard_options_pokemoncard_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemoncard",
            name="card_id",
            field=models.CharField(max_length=50),
        ),
    ]
