# Generated by Django 6.0.1 on 2026-02-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0004_alter_pokemoncard_card_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="binder",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
